:white_check_mark: Update Actions

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,7 +1,7 @@
 # This workflow will build a golang project
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
 
-name: GinDemo build Test
+name: GinDemo build & request test
 
 on:
   push:
@@ -23,6 +23,22 @@ jobs:
 
     - name: Build
       run: go build -v ./...
+
+    - name: Run built binary
+      run: ./GinDemo
+
+    - name: HTTP Get Test
+      run:
+        sleep 5
+
+        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/getTest)
+        if [ $response -eq 200 ]
+        then
+          echo "Test passed"
+        else
+          echo "Test failed"
+          exit 1
+        fi
 
     # -- Add Test file later ... --
     # - name: Test
